### PR TITLE
Bug jobs not showing closes #194

### LINKED ISSUE #194: Jobs not displayed on job listing page and pagination 1 / 0
**Comment from the testing session:**
[Philip]: I created account. Logged in. Clicked on “Find Jobs”. No jobs displayed. (Have not accepted the confirmation mail from sign-in (if there are any?)) (Error message: [blocked]Access to geolocation was blocked over insecure connection to http://localhost:4200. )

### PR DESCRIPTION
**Pull request by Ekman1991**

### CODE REVIEW

File: src/app/views/home/home.component.ts [hunk 1]
```diff
@@ -55,7 +55,7 @@ export class HomeComponent extends TranslationListener implements OnInit {
   }
 
   private loadJobs(): void {
-    this.jobProxy.getJobs({ include: 'company,hourly_pay,company.company_images', 'filter[filled]': false, 'filter[job_date]': yyyymmdd(new Date())  })
+    this.jobProxy.getJobs({ include: 'company,hourly_pay,company.company_images', 'filter[filled]': false, 'filter[job_date]': yyyymmdd(new Date())+'..'+yyyymmdd(nbrOfMonthsFromDate(new Date(), 6))})
```
Comment (bex1) [inline src/app/views/home/home.component.ts:58]: The number 6 months was taken from?
Should likely not be a problem though

**Review by bex1 — APPROVED** [review]
